# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Copyright (C) 2025 word-office

name: Service unit tests
on:
  push:
    branches:
      - '**'
    paths:
      - '**.js'
      - '!tests/integration/**'
      - '!DocService/sources/databaseConnectors/**'
jobs:
  unit-tests:
    name: Service unit tests
    runs-on: docker
    container: node:20-bookworm

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Caching dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            ./npm-shrinkwrap.json
            ./Common/npm-shrinkwrap.json
            ./DocService/npm-shrinkwrap.json
            ./FileConverter/npm-shrinkwrap.json

      - name: Install modules
        run: |
          npm ci
          npm --prefix Common ci
          npm --prefix DocService ci
          npm --prefix FileConverter ci

      - name: Run Jest with coverage and JUnit report
        run: npm run "unit tests" -- --coverage --reporters=default --reporters=jest-junit
        continue-on-error: true

      - name: Upload JUnit test reports
        uses: actions/upload-artifact@v3
        with:
          name: service-junit-${{ github.sha }}
          path: |
            DocService/junit.xml
            **/junit.xml
          if-no-files-found: ignore
          retention-days: 14
        continue-on-error: true

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v3
        with:
          name: service-coverage-${{ github.sha }}
          path: tests/coverage/
          retention-days: 30