/**
 * Type declarations for @world-office/wo-renderer-wasm
 *
 * The actual WASM module is generated by wasm-pack and lives in
 * core/crates/wo-renderer-wasm/pkg/. That directory is excluded from
 * git (standard wasm-pack convention), so TypeScript needs these
 * declarations to resolve imports during typechecking.
 *
 * These types MUST stay in sync with the wasm-pack generated
 * declarations in pkg/wo_renderer_wasm.d.ts.
 */
declare module "@world-office/wo-renderer-wasm/pkg/wo_renderer_wasm" {
  export function init(): void
  export function render_page(
    doc_bytes: Uint8Array,
    format: string,
    width?: number | null,
    height?: number | null,
  ): number
  export function get_pixel_data(handle: number): Uint8Array
  export function release_canvas(handle: number): void
  export function clear_canvas(handle: number): void
  export function create_canvas(width: number, height: number): number
  export function flush_to_canvas(handle: number, canvas_id: string): void
  export function get_canvas_size(handle: number): string
  export function render_rect(
    handle: number,
    x: number,
    y: number,
    w: number,
    h: number,
    color: string,
  ): void
  export function render_text(
    handle: number,
    text: string,
    x: number,
    y: number,
    color?: string | null,
    size?: number | null,
  ): void
}
