/**
 * Mock stub for @world-office/wo-renderer-wasm/pkg/wo_renderer_wasm.js
 *
 * The real WASM module is generated by wasm-pack and only available after
 * running `wasm-pack build` in core/crates/wo-renderer-wasm/. At build
 * time (especially in CI), the pkg/ directory doesn't exist, so Vite
 * needs a resolvable target.
 *
 * Runtime code (wasm-renderer.ts) imports this dynamically with try/catch,
 * so the stub is only used for build resolution — actual rendering uses
 * the real WASM module when available.
 */
export function init(): void {}

export function render_page(
  _doc_bytes: Uint8Array,
  _format: string,
  _width?: number | null,
  _height?: number | null,
): number {
  return -1
}

export function get_pixel_data(_handle: number): Uint8Array {
  return new Uint8Array(0)
}

export function release_canvas(_handle: number): void {}

export function clear_canvas(_handle: number): void {}

export function create_canvas(_width: number, _height: number): number {
  return -1
}

export function flush_to_canvas(_handle: number, _canvas_id: string): void {}

export function get_canvas_size(_handle: number): string {
  return "0,0"
}

export function render_rect(
  _handle: number,
  _x: number,
  _y: number,
  _w: number,
  _h: number,
  _color: string,
): void {}

export function render_text(
  _handle: number,
  _text: string,
  _x: number,
  _y: number,
  _color?: string | null,
  _size?: number | null,
): void {}
