/**
 * Resolution shim for the wasm-bindgen `pkg/wo_renderer_wasm` output.
 *
 * The real module is generated by `wasm-pack build` in this crate and is
 * not available in fresh worktrees/CI. This stub lets TypeScript/Vite
 * resolve the import so tests can `vi.mock` the spell-checking surface
 * (`useSpellchecker` renders through `loadWasm()` which dynamic-imports
 * `pkg/wo_renderer_wasm`). Runtime builds either regenerate this file via
 * wasm-pack (overwriting it) or keep the real pkg/ output.
 */
export function init(): void {}
export function spell_load_dictionary(_aff: Uint8Array, _dic: Uint8Array, _lang: string): void {}
export function spell_check_word(_word: string, _lang: string): boolean {
  return true
}
export function spell_suggest(_word: string, _lang: string): string {
  return "[]"
}
export function spell_check_text(_text: string, _lang: string): string {
  return "[]"
}
export function spell_add_to_user_dict(_word: string, _lang: string): void {}
export function spell_load_hyphenation(_hyph: Uint8Array, _lang: string): void {}
export function spell_hyphenate(_word: string, _lang: string): string {
  return "[]"
}
export function spell_release(_lang: string): void {}
export default async function (): Promise<void> {}
