[package]
name = "wo-visio"
version.workspace = true
edition.workspace = true

[dependencies]
zip = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
quick-xml = { version = "0.37", features = ["serialize"] }
base64 = { workspace = true }
uuid = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }