import type { RibbonGroupSpec, RibbonSpec } from "../types"
import { cloudTab } from "./cloud-spec"

/**
 * Global quick-access groups shown at the trail of OO's Home and Plugins
 * tabs (word count, document language, spell/track status, page fitting
 * and zoom). Shared so both tabs carry identical controls.
 */
export const globalLanguageGroup: RibbonGroupSpec = {
  id: "language",
  label: "Language",
  controls: [
    {
      id: "word-count",
      type: "button",
      icon: "FileText",
      label: "Word count",
      command: "wordCount",
    },
    {
      id: "set-document-language",
      type: "button",
      icon: "Globe",
      label: "English – United States",
      command: "setDocumentLanguage",
    },
    {
      id: "spell-checking",
      type: "checkbox",
      label: "Spell checking",
      checked: (ctx) => ctx.spellcheckEnabled ?? true,
      onChange: () => {},
      command: "toggleSpellCheck",
    },
    {
      id: "track-changes",
      type: "button",
      icon: "Eye",
      label: "Track changes",
      command: "toggleTrackChanges",
    },
  ],
}

export const globalViewGroup: RibbonGroupSpec = {
  id: "view",
  label: "View",
  controls: [
    {
      id: "multiple-pages",
      type: "button",
      icon: "Layout",
      label: "Multiple pages",
      command: "multiplePages",
    },
    {
      id: "fit-to-page",
      type: "button",
      icon: "Maximize",
      label: "Fit to page",
      command: "fitToPage",
    },
    {
      id: "fit-to-width",
      type: "button",
      icon: "Maximize2",
      label: "Fit to width",
      command: "fitToWidth",
    },
    {
      id: "zoom-out",
      type: "button",
      icon: "ZoomOut",
      label: "Zoom out",
      command: "zoomOut",
    },
    {
      id: "zoom-in",
      type: "button",
      icon: "ZoomIn",
      label: "Zoom in",
      command: "zoomIn",
    },
  ],
}

/**
 * Word editor ribbon spec — mirrors ONLYOFFICE Document Editor ribbon 1:1.
 *
 * Tabs: File, Home, Insert, Layout, References, View
 * (Forms and Header/Footer are contextual tabs).
 */
export const wordRibbonSpec: RibbonSpec = {
  tabs: [
    {
      id: "file",
      label: "File",
      // OnlyOffice backstage (File tab) — each button opens the matching
      // FileMenu backstage panel via a real command in word-commands.ts.
      groups: [
        {
          id: "backstage",
          label: "File",
          controls: [
            {
              id: "backstage-back",
              type: "button",
              icon: "ChevronLeft",
              label: "Back",
              command: "back",
            },
            {
              id: "backstage-save",
              type: "button",
              icon: "Save",
              label: "Save",
              command: "save",
            },
            {
              id: "backstage-download-as",
              type: "button",
              icon: "Download",
              label: "Download As",
              command: "downloadAs",
            },
            {
              id: "backstage-print",
              type: "button",
              icon: "Printer",
              label: "Print",
              command: "print",
            },
            {
              id: "backstage-protect",
              type: "button",
              icon: "Lock",
              label: "Protect",
              command: "protect",
            },
            {
              id: "backstage-info",
              type: "button",
              icon: "FileText",
              label: "Info",
              command: "info",
            },
            {
              id: "backstage-advanced-settings",
              type: "button",
              icon: "Settings",
              label: "Advanced Settings",
              command: "advancedSettings",
            },
            {
              id: "backstage-help",
              type: "button",
              icon: "HelpCircle",
              label: "Help",
              command: "help",
            },
            {
              id: "backstage-suggest-feature",
              type: "button",
              icon: "MessageSquare",
              label: "Suggest a Feature",
              command: "suggestFeature",
            },
          ],
        },
      ],
    },

    {
      id: "home",
      label: "Home",
      groups: [
        {
          id: "clipboard",
          label: "Clipboard",
          controls: [
            {
              id: "cut",
              type: "button",
              icon: "Scissors",
              label: "Cut",
              command: "cut",
              shortcut: "Ctrl+X",
            },
            {
              id: "copy",
              type: "button",
              icon: "Copy",
              label: "Copy",
              command: "copy",
              shortcut: "Ctrl+C",
            },
            {
              id: "paste",
              type: "button",
              icon: "ClipboardPaste",
              label: "Paste",
              command: "paste",
              shortcut: "Ctrl+V",
            },
            {
              id: "undo",
              type: "button",
              icon: "Undo2",
              label: "Undo",
              command: "undo",
              shortcut: "Ctrl+Z",
            },
            {
              id: "redo",
              type: "button",
              icon: "Redo2",
              label: "Redo",
              command: "redo",
              shortcut: "Ctrl+Y",
            },
            {
              id: "copy-style",
              type: "button",
              icon: "CopyText",
              label: "Copy style",
              command: "copyStyle",
              shortcut: "Ctrl+Alt+C",
            },
          ],
        },
        {
          id: "font",
          label: "Font",
          controls: [
            {
              id: "increase-font-size",
              type: "button",
              icon: "Type",
              label: "Increment font size",
              command: "increaseFontSize",
              shortcut: "Ctrl+]",
            },
            {
              id: "decrease-font-size",
              type: "button",
              icon: "Type",
              label: "Decrement font size",
              command: "decreaseFontSize",
              shortcut: "Ctrl+[",
            },
            {
              id: "change-case",
              type: "button",
              icon: "Edit3",
              label: "Change case",
              command: "changeCase",
            },
            {
              id: "bold",
              type: "button",
              icon: "Bold",
              label: "Bold",
              command: "bold",
              toggleable: true,
              shortcut: "Ctrl+B",
            },
            {
              id: "italic",
              type: "button",
              icon: "Italic",
              label: "Italic",
              command: "italic",
              toggleable: true,
              shortcut: "Ctrl+I",
            },
            {
              id: "underline",
              type: "button",
              icon: "Underline",
              label: "Underline",
              command: "underline",
              toggleable: true,
              shortcut: "Ctrl+U",
            },
            {
              id: "strikethrough",
              type: "button",
              icon: "Strikethrough",
              label: "Strikethrough",
              command: "strike",
              toggleable: true,
              shortcut: "Ctrl+5",
            },
            {
              id: "superscript",
              type: "button",
              icon: "Superscript",
              label: "Superscript",
              command: "superscript",
              toggleable: true,
              shortcut: "Ctrl+,",
            },
            {
              id: "subscript",
              type: "button",
              icon: "Subscript",
              label: "Subscript",
              command: "subscript",
              toggleable: true,
              shortcut: "Ctrl+.",
            },
            {
              id: "font-family",
              type: "select",
              label: "Font",
              options: [
                { value: "", label: "Font" },
                { value: "Aptos", label: "Aptos" },
                { value: "Calibri", label: "Calibri" },
                { value: "Arial", label: "Arial" },
                { value: "Times New Roman", label: "Times New Roman" },
                { value: "Courier New", label: "Courier New" },
                { value: "Georgia", label: "Georgia" },
                { value: "Verdana", label: "Verdana" },
              ],
              value: () => "",
              onChange: (val: string) =>
                window.dispatchEvent(
                  new CustomEvent("wo-command", { detail: { command: "fontFamily", value: val } }),
                ),
            },
            {
              id: "font-size",
              type: "select",
              label: "",
              options: [
                { value: "", label: "Size" },
                { value: "8pt", label: "8" },
                { value: "9pt", label: "9" },
                { value: "10pt", label: "10" },
                { value: "11pt", label: "11" },
                { value: "12pt", label: "12" },
                { value: "14pt", label: "14" },
                { value: "16pt", label: "16" },
                { value: "18pt", label: "18" },
                { value: "20pt", label: "20" },
                { value: "24pt", label: "24" },
                { value: "28pt", label: "28" },
                { value: "36pt", label: "36" },
                { value: "48pt", label: "48" },
                { value: "72pt", label: "72" },
              ],
              value: () => "",
              onChange: (val: string) =>
                window.dispatchEvent(
                  new CustomEvent("wo-command", { detail: { command: "fontSize", value: val } }),
                ),
              width: 60,
            },
            {
              id: "text-color",
              type: "color-picker",
              label: "Font color",
              color: () => "#000000",
              onChange: (c: string) =>
                window.dispatchEvent(
                  new CustomEvent("wo-command", { detail: { command: "textColor", value: c } }),
                ),
            },
            {
              id: "highlight-color",
              type: "color-picker",
              label: "Highlight color",
              color: () => "#ffff00",
              onChange: (c: string) =>
                window.dispatchEvent(
                  new CustomEvent("wo-command", { detail: { command: "highlight", value: c } }),
                ),
            },
            {
              id: "clear-formatting",
              type: "button",
              icon: "RemoveFormatting",
              label: "Clear style",
              command: "clearFormatting",
            },
          ],
        },
        {
          id: "paragraph",
          label: "Paragraph",
          controls: [
            {
              id: "bullet-list",
              type: "button",
              icon: "List",
              label: "Bullets",
              command: "bulletList",
              toggleable: true,
            },
            {
              id: "ordered-list",
              type: "button",
              icon: "ListOrdered",
              label: "Numbering",
              command: "orderedList",
              toggleable: true,
            },
            {
              id: "task-list",
              type: "button",
              icon: "ListChecks",
              label: "Tasks",
              command: "taskList",
              toggleable: true,
            },
            {
              id: "multilevel-list",
              type: "button",
              icon: "ListOrdered",
              label: "Multilevel list",
              command: "multilevelList",
            },
            {
              id: "outdent",
              type: "button",
              icon: "IndentDecrease",
              label: "Decrease indent",
              command: "outdent",
              shortcut: "Ctrl+Shift+M",
            },
            {
              id: "indent",
              type: "button",
              icon: "IndentIncrease",
              label: "Increase indent",
              command: "indent",
              shortcut: "Ctrl+M",
            },
            {
              id: "line-spacing",
              type: "select",
              label: "Paragraph line spacing",
              options: [
                { value: "1", label: "1.0" },
                { value: "1.15", label: "1.15" },
                { value: "1.5", label: "1.5" },
                { value: "2", label: "2.0" },
                { value: "2.5", label: "2.5" },
                { value: "3", label: "3.0" },
              ],
              value: () => "1.15",
              onChange: (val: string) =>
                window.dispatchEvent(
                  new CustomEvent("wo-command", { detail: { command: "lineSpacing", value: val } }),
                ),
              width: 80,
            },
            {
              id: "text-direction",
              type: "select",
              label: "Text direction",
              options: [
                { value: "", label: "Text direction" },
                { value: "ltr", label: "Left-to-right" },
                { value: "rtl", label: "Right-to-left" },
              ],
              value: () => "",
              onChange: (val: string) =>
                window.dispatchEvent(
                  new CustomEvent("wo-command", {
                    detail: { command: "setTextDirection", value: val },
                  }),
                ),
              width: 110,
            },
            {
              id: "align-left",
              type: "button",
              icon: "AlignLeft",
              label: "Align left",
              command: "alignLeft",
              toggleable: true,
              shortcut: "Ctrl+L",
            },
            {
              id: "align-center",
              type: "button",
              icon: "AlignCenter",
              label: "Align center",
              command: "alignCenter",
              toggleable: true,
              shortcut: "Ctrl+E",
            },
            {
              id: "align-right",
              type: "button",
              icon: "AlignRight",
              label: "Align right",
              command: "alignRight",
              toggleable: true,
              shortcut: "Ctrl+R",
            },
            {
              id: "align-justify",
              type: "button",
              icon: "AlignJustify",
              label: "Justified",
              command: "alignJustify",
              toggleable: true,
              shortcut: "Ctrl+J",
            },
            {
              id: "nonprinting",
              type: "button",
              icon: "Eye",
              label: "Nonprinting characters",
              command: "toggleNonprinting",
              shortcut: "Ctrl+Shift+8",
            },
            {
              id: "shading",
              type: "button",
              icon: "PaintBucket",
              label: "Shading",
              command: "shading",
            },
            {
              id: "borders",
              type: "button",
              icon: "Square",
              label: "Borders",
              command: "borders",
            },
          ],
        },
        {
          id: "styles",
          label: "Styles",
          controls: [
            { id: "heading1", type: "button", icon: "Heading1", label: "H1", command: "heading1" },
            { id: "heading2", type: "button", icon: "Heading2", label: "H2", command: "heading2" },
            { id: "heading3", type: "button", icon: "Heading3", label: "H3", command: "heading3" },
            {
              id: "blockquote",
              type: "button",
              icon: "TextQuote",
              label: "Quote",
              command: "blockquote",
            },
            {
              id: "code-block",
              type: "button",
              icon: "Code2",
              label: "Code",
              command: "codeBlock",
            },
          ],
        },
        {
          id: "editing",
          label: "Editing",
          controls: [
            {
              id: "find",
              type: "button",
              icon: "Search",
              label: "Find",
              command: "find",
              shortcut: "Ctrl+F",
            },
            {
              id: "replace",
              type: "button",
              icon: "Replace",
              label: "Replace",
              command: "replace",
              shortcut: "Ctrl+H",
            },
            {
              id: "select-all",
              type: "button",
              icon: "MousePointer",
              label: "Select all",
              command: "selectAll",
              shortcut: "Ctrl+A",
            },
          ],
        },
        globalLanguageGroup,
        globalViewGroup,
      ],
    },

    {
      id: "insert",
      label: "Insert",
      visible: (ctx) => ctx.isEditMode,
      groups: [
        {
          id: "pages",
          label: "Pages",
          controls: [
            {
              id: "blank-page",
              type: "button",
              icon: "SquarePlus",
              label: "Blank Page",
              command: "blankPage",
            },
            {
              id: "page-break",
              type: "button",
              icon: "Minus",
              label: "Breaks",
              command: "pageBreak",
            },
          ],
        },
        {
          id: "table",
          label: "Table",
          controls: [
            {
              id: "insert-table",
              type: "button",
              icon: "Table2",
              label: "Table",
              command: "insertTable",
            },
          ],
        },
        {
          id: "media",
          label: "Media",
          controls: [
            { id: "insert-image", type: "button", icon: "Image", label: "Image", command: "image" },
            {
              id: "insert-shape",
              type: "button",
              icon: "Shapes",
              label: "Shape",
              command: "insertShape",
            },
            {
              id: "insert-smart-art",
              type: "button",
              icon: "Layers",
              label: "SmartArt",
              command: "insertSmartArt",
            },
            {
              id: "insert-chart",
              type: "button",
              icon: "BarChart3",
              label: "Chart",
              command: "insertChart",
            },
          ],
        },
        {
          id: "links",
          label: "Links",
          controls: [
            {
              id: "insert-link",
              type: "button",
              icon: "Globe",
              label: "Link",
              command: "link",
              shortcut: "Ctrl+K",
            },
          ],
        },
        {
          id: "text",
          label: "Text",
          controls: [
            {
              id: "horizontal-rule",
              type: "button",
              icon: "Minus",
              label: "HR",
              command: "horizontalRule",
            },
            {
              id: "insert-text-box",
              type: "button",
              icon: "TextCursorInput",
              label: "Text Box",
              command: "textBox",
            },
            {
              id: "insert-text-art",
              type: "button",
              icon: "Type",
              label: "Text Art",
              command: "textArt",
            },
            {
              id: "insert-drop-cap",
              type: "button",
              icon: "Text",
              label: "Drop Cap",
              command: "dropCap",
            },
            {
              id: "text-from-file",
              type: "button",
              icon: "FileText",
              label: "Text from File",
              command: "textFromFile",
            },
          ],
        },
        {
          id: "objects",
          label: "Objects",
          controls: [
            {
              id: "insert-equation",
              type: "button",
              icon: "Sigma",
              label: "Equation",
              command: "equation",
            },
            {
              id: "insert-symbol",
              type: "button",
              icon: "Omega",
              label: "Symbol",
              command: "symbol",
            },
          ],
        },
        {
          id: "content-controls",
          label: "Content Controls",
          controls: [
            {
              id: "insert-content-control",
              type: "button",
              icon: "CheckSquare",
              label: "Content Controls",
              command: "insertContentControl",
            },
          ],
        },
      ],
    },

    {
      id: "layout",
      label: "Layout",
      visible: (ctx) => ctx.isEditMode,
      groups: [
        {
          id: "page-setup",
          label: "Page Setup",
          controls: [
            {
              id: "page-orientation",
              type: "button",
              icon: "File",
              label: "Orientation",
              command: "pageOrientation",
            },
            { id: "page-size", type: "button", icon: "File", label: "Size", command: "pageSize" },
            {
              id: "page-margins",
              type: "button",
              icon: "File",
              label: "Margins",
              command: "pageMargins",
            },
            {
              id: "columns",
              type: "button",
              icon: "AlignJustify",
              label: "Columns",
              command: "columns",
            },
            {
              id: "line-numbers",
              type: "button",
              icon: "ListOrdered",
              label: "Line Numbers",
              command: "lineNumbers",
              toggleable: true,
            },
            {
              id: "hyphenation",
              type: "button",
              icon: "Minus",
              label: "Hyphenation",
              command: "hyphenation",
            },
            {
              id: "wrapping",
              type: "button",
              icon: "AlignJustify",
              label: "Wrapping",
              command: "wrapping",
            },
          ],
        },
        {
          id: "arrange",
          label: "Arrange",
          controls: [
            {
              id: "bring-forward",
              type: "button",
              icon: "ChevronUp",
              label: "Bring Forward",
              command: "bringForward",
            },
            {
              id: "send-backward",
              type: "button",
              icon: "ChevronDown",
              label: "Send Backward",
              command: "sendBackward",
            },
            {
              id: "align",
              type: "button",
              icon: "AlignCenter",
              label: "Align",
              command: "alignObjects",
            },
            {
              id: "group",
              type: "button",
              icon: "Layers",
              label: "Group",
              command: "groupObjects",
            },
            {
              id: "merge-shapes",
              type: "button",
              icon: "Combine",
              label: "Merge Shapes",
              command: "mergeShapes",
            },
          ],
        },
        {
          id: "page-background",
          label: "Page Background",
          controls: [
            {
              id: "watermark",
              type: "button",
              icon: "Image",
              label: "Watermark",
              command: "watermark",
            },
            {
              id: "page-color",
              type: "button",
              icon: "StopCircle",
              label: "Page Color",
              command: "pageColor",
            },
            {
              id: "colors",
              type: "button",
              icon: "Palette",
              label: "Colors",
              command: "documentColors",
            },
          ],
        },
        {
          id: "breaks",
          label: "Breaks",
          controls: [
            {
              id: "breaks",
              type: "button",
              icon: "Remove",
              label: "Breaks",
              command: "openBreaksPanel",
            },
          ],
        },
        {
          id: "theme",
          label: "Theme",
          controls: [
            {
              id: "document-theme",
              type: "button",
              icon: "StopCircle",
              label: "Theme",
              command: "openTheme",
            },
          ],
        },
        {
          id: "header-footer",
          label: "Header & Footer",
          controls: [
            {
              id: "edit-header",
              type: "button",
              icon: "AlignJustify",
              label: "Header",
              command: "editHeader",
            },
            {
              id: "edit-footer",
              type: "button",
              icon: "AlignJustify",
              label: "Footer",
              command: "editFooter",
            },
            {
              id: "insert-page-number",
              type: "button",
              icon: "Hash",
              label: "Page Number",
              command: "insertPageNumber",
            },
            {
              id: "insert-date-time",
              type: "button",
              icon: "CalendarDays",
              label: "Date & Time",
              command: "insertDateTime",
            },
            {
              id: "insert-field",
              type: "button",
              icon: "Braces",
              label: "Field",
              command: "insertField",
            },
            {
              id: "close-header-footer",
              type: "button",
              icon: "X",
              label: "Close",
              command: "closeHeaderFooter",
            },
            {
              id: "different-first-page",
              type: "checkbox",
              label: "Different First Page",
              checked: (ctx) => ctx.differentFirstPage ?? false,
              onChange: () => {},
              command: "differentFirstPage",
            },
            {
              id: "different-odd-even",
              type: "checkbox",
              label: "Different Odd & Even",
              checked: (ctx) => ctx.differentOddEven ?? false,
              onChange: () => {},
              command: "differentOddEven",
            },
            {
              id: "remove-header",
              type: "button",
              icon: "Trash2",
              label: "Remove Header",
              command: "removeHeader",
            },
            {
              id: "remove-footer",
              type: "button",
              icon: "Trash2",
              label: "Remove Footer",
              command: "removeFooter",
            },
          ],
        },
      ],
    },

    {
      id: "references",
      label: "References",
      groups: [
        {
          id: "toc",
          label: "Table of Contents",
          controls: [
            {
              id: "insert-toc",
              type: "button",
              icon: "List",
              label: "Table of Contents",
              command: "insertToc",
            },
            {
              id: "add-toc-text",
              type: "button",
              icon: "Type",
              label: "Add Text",
              command: "addTocText",
            },
            {
              id: "update-toc",
              type: "button",
              icon: "Replace",
              label: "Update Table",
              command: "updateToc",
            },
          ],
        },
        {
          id: "footnotes",
          label: "Footnotes",
          controls: [
            {
              id: "insert-footnote",
              type: "button",
              icon: "Plus",
              label: "Footnote",
              command: "insertFootnote",
            },
            {
              id: "insert-endnote",
              type: "button",
              icon: "Plus",
              label: "Endnote",
              command: "insertEndnote",
            },
          ],
        },
        {
          id: "captions",
          label: "Captions",
          controls: [
            {
              id: "insert-bookmark",
              type: "button",
              icon: "MapPin",
              label: "Bookmark",
              command: "insertBookmark",
            },
            {
              id: "insert-caption",
              type: "button",
              icon: "MessageSquare",
              label: "Caption",
              command: "insertCaption",
            },
            {
              id: "insert-cross-reference",
              type: "button",
              icon: "ArrowLeftRight",
              label: "Cross-reference",
              command: "insertCrossReference",
            },
            {
              id: "insert-table-of-figures",
              type: "button",
              icon: "Table2",
              label: "Table of Figures",
              command: "insertTableOfFigures",
            },
          ],
        },
        {
          id: "comments",
          label: "Comments",
          controls: [
            {
              id: "add-comment",
              type: "button",
              icon: "TextQuote",
              label: "Comment",
              command: "addComment",
            },
            {
              id: "toggle-comment",
              type: "button",
              icon: "X",
              label: "Remove",
              command: "toggleComment",
            },
          ],
        },
        {
          id: "index",
          label: "Index",
          controls: [
            {
              id: "mark-index-entry",
              type: "button",
              icon: "Plus",
              label: "Mark Entry",
              command: "insertIndexEntry",
            },
            {
              id: "insert-index",
              type: "button",
              icon: "List",
              label: "Insert Index",
              command: "insertIndex",
            },
            {
              id: "update-index",
              type: "button",
              icon: "Replace",
              label: "Update Index",
              command: "updateIndex",
            },
          ],
        },
      ],
    },

    {
      id: "collaboration",
      label: "Collaboration",
      groups: [
        {
          id: "tracking",
          label: "Tracking",
          controls: [
            {
              id: "track-changes",
              type: "button",
              icon: "Eye",
              label: "Track Changes",
              command: "toggleTrackChanges",
            },
          ],
        },
        {
          id: "changes",
          label: "Changes",
          controls: [
            {
              id: "accept-change",
              type: "button",
              icon: "Check",
              label: "Accept",
              command: "acceptChange",
            },
            {
              id: "reject-change",
              type: "button",
              icon: "X",
              label: "Reject",
              command: "rejectChange",
            },
            {
              id: "accept-all",
              type: "button",
              icon: "CheckCheck",
              label: "Accept All",
              command: "acceptAllChanges",
            },
            {
              id: "reject-all",
              type: "button",
              icon: "XCircle",
              label: "Reject All",
              command: "rejectAllChanges",
            },
            {
              id: "previous-change",
              type: "button",
              icon: "ChevronLeft",
              label: "Previous",
              command: "previousChange",
            },
            {
              id: "next-change",
              type: "button",
              icon: "ChevronRight",
              label: "Next",
              command: "nextChange",
            },
          ],
        },
        {
          id: "comments",
          label: "Comments",
          controls: [
            {
              id: "add-comment",
              type: "button",
              icon: "Plus",
              label: "Add Comment",
              command: "addComment",
            },
            {
              id: "delete-comment",
              type: "button",
              icon: "Trash2",
              label: "Delete",
              command: "deleteComment",
            },
            {
              id: "resolve-comment",
              type: "button",
              icon: "Check",
              label: "Resolve",
              command: "resolveComment",
            },
            {
              id: "comments-panel",
              type: "button",
              icon: "MessageSquare",
              label: "Comments",
              command: "toggleComment",
            },
          ],
        },
        {
          id: "display",
          label: "Display",
          controls: [
            {
              id: "display-mode",
              type: "button",
              icon: "LayoutDashboard",
              label: "Display Mode",
              command: "displayMode",
            },
          ],
        },
        {
          id: "compare",
          label: "Compare",
          controls: [
            {
              id: "compare-documents",
              type: "button",
              icon: "FileDiff",
              label: "Compare",
              command: "compareDocuments",
            },
            {
              id: "combine-documents",
              type: "button",
              icon: "Merge",
              label: "Combine",
              command: "combineDocuments",
            },
          ],
        },
        {
          id: "mail-merge",
          label: "Mail Merge",
          controls: [
            {
              id: "mail-merge",
              type: "button",
              icon: "Mail",
              label: "Mail Merge",
              command: "mailMerge",
            },
          ],
        },
        {
          id: "chat",
          label: "Chat",
          controls: [
            {
              id: "chat-panel",
              type: "button",
              icon: "Users",
              label: "Chat",
              command: "chat",
            },
          ],
        },
      ],
    },

    {
      id: "protection",
      label: "Protection",
      groups: [
        {
          id: "protect",
          label: "Protect",
          controls: [
            {
              id: "protect-document",
              type: "button",
              icon: "Lock",
              label: "Protect Document",
              command: "protect-document",
            },
            {
              id: "encrypt",
              type: "button",
              icon: "LockKey",
              label: "Encrypt",
              command: "encrypt",
            },
          ],
        },
      ],
    },

    {
      id: "draw",
      label: "Draw",
      visible: (ctx) => ctx.isEditMode,
      groups: [
        {
          id: "draw-clipboard",
          label: "Clipboard",
          controls: [
            {
              id: "draw-cut",
              type: "button",
              icon: "Scissors",
              label: "Cut",
              command: "cut",
              shortcut: "Ctrl+X",
            },
            {
              id: "draw-copy",
              type: "button",
              icon: "Copy",
              label: "Copy",
              command: "copy",
              shortcut: "Ctrl+C",
            },
            {
              id: "draw-paste",
              type: "button",
              icon: "ClipboardPaste",
              label: "Paste",
              command: "paste",
              shortcut: "Ctrl+V",
            },
            {
              id: "draw-copy-style",
              type: "button",
              icon: "Copy",
              label: "Copy style",
              command: "copyStyle",
              shortcut: "Ctrl+Alt+C",
            },
          ],
        },
        {
          id: "draw-tools",
          label: "Tools",
          controls: [
            {
              id: "draw-select",
              type: "button",
              icon: "MousePointer2",
              label: "Select",
              command: "drawSelect",
            },
            {
              id: "draw-eraser",
              type: "button",
              icon: "Eraser",
              label: "Eraser",
              command: "drawEraser",
            },
          ],
        },
        {
          id: "draw-info",
          label: "Info",
          controls: [
            {
              id: "draw-word-count",
              type: "button",
              icon: "FileText",
              label: "Word count",
              command: "wordCount",
            },
          ],
        },
        {
          id: "draw-language",
          label: "Language",
          controls: [
            {
              id: "draw-language-select",
              type: "select",
              label: "English – United States",
              options: [
                { value: "en-US", label: "English – United States" },
                { value: "en-GB", label: "English – United Kingdom" },
                { value: "de-DE", label: "German" },
                { value: "fr-FR", label: "French" },
              ],
              value: () => "en-US",
              onChange: (val: string) =>
                window.dispatchEvent(
                  new CustomEvent("wo-command", { detail: { command: "setDocumentLanguage", value: val } }),
                ),
            },
            {
              id: "draw-set-language",
              type: "button",
              icon: "Globe",
              label: "Set document language",
              command: "setDocumentLanguage",
            },
            {
              id: "draw-spell-checking",
              type: "checkbox",
              label: "Spell checking",
              checked: (ctx) => ctx.spellcheckEnabled ?? true,
              onChange: () => {},
              command: "toggleSpellCheck",
            },
          ],
        },
        {
          id: "draw-review",
          label: "Review",
          controls: [
            {
              id: "draw-track-changes",
              type: "checkbox",
              label: "Track changes",
              checked: (ctx) => ctx.trackChangesEnabled ?? false,
              onChange: () => {},
              command: "toggleTrackChanges",
            },
          ],
        },
        {
          id: "draw-view",
          label: "View",
          controls: [
            {
              id: "draw-multiple-pages",
              type: "button",
              icon: "Layout",
              label: "Multiple pages",
              command: "toggleMultiplePages",
            },
            {
              id: "draw-fit-to-page",
              type: "button",
              icon: "Maximize",
              label: "Fit to page",
              command: "fitToPage",
            },
            {
              id: "draw-fit-to-width",
              type: "button",
              icon: "Maximize",
              label: "Fit to width",
              command: "fitToWidth",
            },
            {
              id: "draw-zoom-out",
              type: "button",
              icon: "ZoomOut",
              label: "Zoom out",
              command: "zoomOut",
              shortcut: "Ctrl+-",
            },
            {
              id: "draw-zoom-in",
              type: "button",
              icon: "ZoomIn",
              label: "Zoom in",
              command: "zoomIn",
              shortcut: "Ctrl+Num +",
            },
          ],
        },
      ],
    },

    {
      id: "view",
      label: "View",
      groups: [
        {
          id: "zoom",
          label: "Zoom",
          controls: [
            { id: "zoom-in", type: "button", icon: "ZoomIn", label: "Zoom In", command: "zoomIn" },
            {
              id: "zoom-out",
              type: "button",
              icon: "ZoomOut",
              label: "Zoom Out",
              command: "zoomOut",
            },
            {
              id: "zoom-100",
              type: "button",
              icon: "Percent",
              label: "Zoom to 100%",
              command: "zoomTo100",
            },
          ],
        },
        {
          id: "show",
          label: "Show",
          controls: [
            {
              id: "spellcheck",
              type: "checkbox",
              label: "Spell Check",
              checked: (ctx) => ctx.spellcheckEnabled ?? true,
              onChange: () => {},
              command: "toggleSpellCheck",
            },
            {
              id: "ruler",
              type: "checkbox",
              label: "Ruler",
              checked: (ctx) => ctx.rulerVisible ?? true,
              onChange: () => {},
              command: "toggleRuler",
            },
            {
              id: "gridlines",
              type: "checkbox",
              label: "Gridlines",
              checked: (ctx) => ctx.gridlinesVisible ?? false,
              onChange: () => {},
              command: "toggleGridlines",
            },
            {
              id: "navigation",
              type: "checkbox",
              label: "Headings",
              checked: (ctx) => ctx.navigationVisible ?? false,
              onChange: () => {},
              command: "toggleNavigation",
            },
            {
              id: "dark-document",
              type: "checkbox",
              label: "Dark Document",
              checked: (ctx) => ctx.darkDocument ?? false,
              onChange: () => {},
              command: "toggleDarkDocument",
            },
          ],
        },
        {
          id: "interface-theme",
          label: "Interface Theme",
          controls: [
            {
              id: "interface-theme",
              type: "select",
              label: "Interface Theme",
              options: [
                { value: "office", label: "Light" },
                { value: "classic", label: "Classic Light" },
                { value: "dark", label: "Dark" },
                { value: "contrast", label: "Contrast Black" },
              ],
              value: () => "office",
              onChange: (val: string) =>
                window.dispatchEvent(
                  new CustomEvent("wo-command", {
                    detail: { command: "interfaceTheme", value: val },
                  }),
                ),
            },
          ],
        },
        {
          id: "macros",
          label: "Macros",
          controls: [
            {
              id: "macros",
              type: "button",
              icon: "Code2",
              label: "Macros",
              command: "macros",
            },
            {
              id: "record-macro",
              type: "button",
              icon: "Play",
              label: "Record Macro",
              command: "recordMacro",
            },
            {
              id: "pause-recording",
              type: "button",
              icon: "Timer",
              label: "Pause Recording",
              command: "pauseMacroRecording",
            },
          ],
        },
      ],
    },

    {
      id: "forms",
      label: "Forms",
      groups: [
        {
          id: "form-controls",
          label: "Form Controls",
          controls: [
            {
              id: "text-input",
              type: "button",
              icon: "TextCursorInput",
              label: "Text Input",
              command: "insertPlainTextControl",
            },
            {
              id: "checkbox-control",
              type: "button",
              icon: "CheckSquare",
              label: "Checkbox",
              command: "insertCheckboxControl",
            },
            {
              id: "dropdown",
              type: "button",
              icon: "ChevronDown",
              label: "Dropdown",
              command: "insertDropdownControl",
            },
            {
              id: "date-picker",
              type: "button",
              icon: "Calendar",
              label: "Date Picker",
              command: "insertDatePickerControl",
            },
            {
              id: "combo-box",
              type: "button",
              icon: "ChevronDown",
              label: "Combo Box",
              command: "insertDropdownControl",
            },
          ],
        },
      ],
    },

    {
      id: "plugins",
      label: "Plugins",
      groups: [
        {
          id: "clipboard",
          label: "Clipboard",
          controls: [
            {
              id: "plugins-cut",
              type: "button",
              icon: "Scissors",
              label: "Cut",
              command: "cut",
              shortcut: "Ctrl+X",
            },
            {
              id: "plugins-copy",
              type: "button",
              icon: "Copy",
              label: "Copy",
              command: "copy",
              shortcut: "Ctrl+C",
            },
            {
              id: "plugins-paste",
              type: "button",
              icon: "ClipboardPaste",
              label: "Paste",
              command: "paste",
              shortcut: "Ctrl+V",
            },
            {
              id: "copy-style",
              type: "button",
              icon: "CopyText",
              label: "Copy style",
              command: "copyStyle",
            },
          ],
        },
        {
          id: "plugin-tools",
          label: "Tools",
          controls: [
            {
              id: "plugin-manager",
              type: "button",
              icon: "Settings",
              label: "PluginManager",
              command: "pluginManager",
            },
            {
              id: "background-plugins",
              type: "button",
              icon: "Layers",
              label: "Backgroundplugins",
              command: "backgroundPlugins",
            },
            {
              id: "photo-editor",
              type: "button",
              icon: "Image",
              label: "PhotoEditor",
              command: "photoEditor",
            },
            {
              id: "youtube",
              type: "button",
              icon: "Youtube",
              label: "YouTube",
              command: "youtube",
            },
            {
              id: "ocr",
              type: "button",
              icon: "Text",
              label: "OCR",
              command: "ocr",
            },
            {
              id: "translator",
              type: "button",
              icon: "Languages",
              label: "Translator",
              command: "translator",
            },
            {
              id: "mendeley",
              type: "button",
              icon: "Book",
              label: "Mendeley",
              command: "mendeley",
            },
            {
              id: "thesaurus",
              type: "button",
              icon: "BookOpen",
              label: "Thesaurus",
              command: "thesaurus",
            },
            {
              id: "highlight-code",
              type: "button",
              icon: "Code2",
              label: "Highlightcode",
              command: "highlightCode",
            },
            {
              id: "zotero",
              type: "button",
              icon: "Zap",
              label: "Zotero",
              command: "zotero",
            },
            {
              id: "speech",
              type: "button",
              icon: "Mic",
              label: "Speech",
              command: "speech",
            },
            {
              id: "speech-input",
              type: "button",
              icon: "Mic2",
              label: "Speechinput",
              command: "speechInput",
            },
          ],
        },
        {
          id: "language",
          label: "Language",
          controls: globalLanguageGroup.controls,
        },
        {
          id: "view",
          label: "View",
          controls: globalViewGroup.controls,
        },
      ],
    },

    {
      id: "ai",
      label: "AI",
      groups: [
        {
          id: "ai-assistant",
          label: "AI Assistant",
          controls: [
            {
              id: "ai-settings",
              type: "button",
              icon: "Settings",
              label: "Settings",
              command: "aiSettings",
            },
            {
              id: "ai-chatbot",
              type: "button",
              icon: "MessageSquare",
              label: "Chatbot",
              command: "aiChatbot",
            },
            {
              id: "ai-summarization",
              type: "button",
              icon: "FileText",
              label: "Summarization",
              command: "aiSummarization",
            },
            {
              id: "ai-translation",
              type: "button",
              icon: "Globe",
              label: "Translation",
              command: "aiTranslation",
            },
            {
              id: "ai-grammar-spelling",
              type: "button",
              icon: "CheckCircle",
              label: "Grammar &Spelling",
              command: "aiGrammarSpelling",
            },
            {
              id: "ai-assistant-panel",
              type: "button",
              icon: "Smile",
              label: "Create AIassistant",
              command: "ai-assistant",
            },
          ],
        },
      ],
    },

    cloudTab,
  ],
}
